services:
  - type: web
    name: Organic_v-s_Recyclable_Classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    runtime: python-3.10.13
