services:
  - type: web
    name: organic-classifier
    env: python
    plan: free
    buildCommand: |
      echo "Python Version:" $(python --version)
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    runtime: python-3.10.13
